#!/usr/bin/env python3
"""
scripts/ui/testid_catalog.py  (v4.87.0 — Wave 36)

Generates docs/TESTIDS.md — a catalog of all data-testid values
used across the RiskCanvas web app.

Usage: python3 scripts/ui/testid_catalog.py
"""

import re
import sys
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).resolve().parent.parent.parent
SRC_DIR = ROOT / "apps" / "web" / "src"
OUTPUT = ROOT / "docs" / "TESTIDS.md"

TESTID_RE = re.compile(r'data-testid[=\s{]+["\']([^"\']+)["\']')


def collect_testids() -> dict[str, list[str]]:
    """Returns {relative_file_path: [testid1, testid2, ...]}"""
    result: dict[str, list[str]] = defaultdict(list)
    for tsx in sorted(SRC_DIR.rglob("*.tsx")):
        content = tsx.read_text(encoding="utf-8")
        ids = TESTID_RE.findall(content)
        if ids:
            rel = str(tsx.relative_to(ROOT))
            result[rel].extend(ids)
    return dict(result)


def write_catalog(testids: dict[str, list[str]]) -> None:
    lines = [
        "# RiskCanvas — Data TestID Catalog",
        "",
        "> Generated by `scripts/ui/testid_catalog.py`",
        "> Wave 36 · v4.87.0",
        "",
        f"**Total files with testids:** {len(testids)}",
        f"**Total testid values:** {sum(len(v) for v in testids.values())}",
        "",
        "---",
        "",
    ]

    for filepath, ids in sorted(testids.items()):
        lines.append(f"## `{filepath}`")
        lines.append("")
        for tid in sorted(set(ids)):
            lines.append(f"- `{tid}`")
        lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"✓ Wrote {OUTPUT} ({sum(len(v) for v in testids.values())} testids)")


def main() -> int:
    testids = collect_testids()
    write_catalog(testids)
    print(f"PASS: Catalog generated at {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
