# run_wave9_10.ps1
# Full proof runner for Wave 9+10 (v3.7.0 → v4.0.0)
# Usage: .\scripts\run_wave9_10.ps1
# Produces: artifacts/proof/<timestamp>-wave9-10-v3.7-4.0/

$ErrorActionPreference = "Stop"
$ROOT = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$TS = Get-Date -Format "yyyyMMdd-HHmmss"
$PROOF_DIR = "$ROOT\artifacts\proof\$TS-wave9-10-v3.7-4.0"
$MANIFEST_FILE = "$PROOF_DIR\MANIFEST.md"

Write-Host "=== Wave 9+10 Proof Runner ===" -ForegroundColor Cyan
Write-Host "Root: $ROOT"
Write-Host "Proof dir: $PROOF_DIR"
New-Item -ItemType Directory -Force -Path $PROOF_DIR | Out-Null
New-Item -ItemType Directory -Force -Path "$PROOF_DIR\logs" | Out-Null
New-Item -ItemType Directory -Force -Path "$PROOF_DIR\screenshots" | Out-Null

# ── Step 1: Engine tests ──────────────────────────────────────────────────────
Write-Host "`n[1/5] Engine tests..." -ForegroundColor Yellow
Set-Location "$ROOT\packages\engine"
$engineLog = "$PROOF_DIR\logs\engine-pytest.txt"
python -m pytest tests/ -q --tb=short 2>&1 | Tee-Object -FilePath $engineLog
if ($LASTEXITCODE -ne 0) { Write-Error "Engine tests FAILED"; exit 1 }
Write-Host "Engine tests PASSED" -ForegroundColor Green

# ── Step 2: Backend pytest ────────────────────────────────────────────────────
Write-Host "`n[2/5] Backend pytest..." -ForegroundColor Yellow
Set-Location "$ROOT\apps\api"
$env:DEMO_MODE = "true"
$env:PYTHONPATH = "$ROOT\packages\engine"
$backendLog = "$PROOF_DIR\logs\backend-pytest.txt"
python -m pytest tests/ -q --tb=short 2>&1 | Tee-Object -FilePath $backendLog
if ($LASTEXITCODE -ne 0) { Write-Error "Backend tests FAILED"; exit 1 }
Write-Host "Backend tests PASSED" -ForegroundColor Green

# ── Step 3: Vitest ────────────────────────────────────────────────────────────
Write-Host "`n[3/5] Vitest..." -ForegroundColor Yellow
Set-Location "$ROOT\apps\web"
$vitestLog = "$PROOF_DIR\logs\vitest.txt"
npx vitest run 2>&1 | Tee-Object -FilePath $vitestLog
if ($LASTEXITCODE -ne 0) { Write-Error "Vitest FAILED"; exit 1 }
Write-Host "Vitest PASSED" -ForegroundColor Green

# ── Step 4: TypeScript + vite build ──────────────────────────────────────────
Write-Host "`n[4/5] TypeScript + vite build..." -ForegroundColor Yellow
$tscLog = "$PROOF_DIR\logs\tsc.txt"
npx tsc --noEmit 2>&1 | Tee-Object -FilePath $tscLog
if ($LASTEXITCODE -ne 0) { Write-Error "TypeScript FAILED"; exit 1 }
$buildLog = "$PROOF_DIR\logs\vite-build.txt"
npm run build 2>&1 | Tee-Object -FilePath $buildLog
if ($LASTEXITCODE -ne 0) { Write-Error "Vite build FAILED"; exit 1 }
Write-Host "TS + Build PASSED" -ForegroundColor Green

# ── Step 5: Generate MANIFEST.md ─────────────────────────────────────────────
Write-Host "`n[5/5] Generating manifest..." -ForegroundColor Yellow
$backendLines = Get-Content $backendLog | Select-String "passed|failed"
$engineLines = Get-Content $engineLog | Select-String "passed|failed"
$vitestLines = Get-Content $vitestLog | Select-String "Tests"

$manifest = @"
# Wave 9+10 Proof Manifest

**Generated:** $TS
**Version:** v3.7.0 → v4.0.0

## Test Results

### Backend (pytest)
$($backendLines -join "`n")

### Engine (pytest)
$($engineLines -join "`n")

### Vitest
$($vitestLines -join "`n")

## New Files (Wave 9+10)

### Backend
- apps/api/policy_engine.py (v3.7 PolicyEngine v2)
- apps/api/eval_harness_v2.py (v3.8 Eval Harness v2)
- apps/api/devops_pro.py (v3.9 DevOps Pro)
- apps/api/sre_playbook.py (v4.0 SRE Playbooks)
- apps/api/tests/test_policy_engine.py
- apps/api/tests/test_eval_harness_v2.py
- apps/api/tests/test_devops_pro.py
- apps/api/tests/test_sre_playbook.py

### Frontend
- apps/web/src/pages/SREPlaybooksPage.tsx (NEW)
- apps/web/src/pages/GovernancePage.tsx (updated – 4 tabs)
- apps/web/src/pages/DevOpsPage.tsx (updated – 3 new tabs)
- apps/web/src/components/layout/AppLayout.tsx (v4.0.0, nav-sre)
- apps/web/src/App.tsx (/sre route)
- apps/web/src/lib/api.ts (new functions)

### E2E
- e2e/test-governance-policy.spec.ts (8 tests)
- e2e/test-devops-pro.spec.ts (8 tests)
- e2e/test-sre-playbooks.spec.ts (8 tests)
- e2e/phase10-judge-demo.spec.ts (28 screenshots)
- e2e/playwright.w9w10.judge.config.ts

## MANIFEST Hash
Generated by run_wave9_10.ps1
"@

$manifest | Set-Content $MANIFEST_FILE

Write-Host "`n=== Wave 9+10 Proof COMPLETE ===" -ForegroundColor Green
Write-Host "Proof dir: $PROOF_DIR" -ForegroundColor Cyan
Write-Host "Run E2E manually: cd e2e; npx playwright test --config playwright.config.ts test-governance-policy.spec.ts test-devops-pro.spec.ts test-sre-playbooks.spec.ts"
